apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andresramilo/web-page-deploy.git
    path: kustomize
    targetRevision: HEAD
  destination:
    namespace: conversao
    server: https://kubernetes.default.svc
